apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sherinascdlm/ecom-test-microservice-auth-service:v1
          ports:
            - containerPort: 50051
          env:
            - name: POSTGRES_USER
              value: "sherinascdlm"
            - name: POSTGRES_PASSWORD
              value: "admin123"
            - name: POSTGRES_HOST
              value: "postgres-database"
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_SECRET
              value: "your-secret-key"
            - name: ADMIN_SECRET
              value: "your-admin-secret-key"
            - name: AUTH_PORT
              value: "50051"
