// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: pb/proto/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAddProductRequest) Reset() {
	*x = AdminAddProductRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddProductRequest) ProtoMessage() {}

func (x *AdminAddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddProductRequest.ProtoReflect.Descriptor instead.
func (*AdminAddProductRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminAddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminAddProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AdminAddProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AdminAddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAddProductResponse) Reset() {
	*x = AdminAddProductResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddProductResponse) ProtoMessage() {}

func (x *AdminAddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddProductResponse.ProtoReflect.Descriptor instead.
func (*AdminAddProductResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminAddProductResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateProductRequest) Reset() {
	*x = AdminUpdateProductRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateProductRequest) ProtoMessage() {}

func (x *AdminUpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateProductRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AdminUpdateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AdminUpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateProductResponse) Reset() {
	*x = AdminUpdateProductResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateProductResponse) ProtoMessage() {}

func (x *AdminUpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateProductResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUpdateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminDeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteProductRequest) Reset() {
	*x = AdminDeleteProductRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteProductRequest) ProtoMessage() {}

func (x *AdminDeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteProductRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminDeleteProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteProductResponse) Reset() {
	*x = AdminDeleteProductResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteProductResponse) ProtoMessage() {}

func (x *AdminDeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteProductResponse.ProtoReflect.Descriptor instead.
func (*AdminDeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminDeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminListAllProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListAllProductsRequest) Reset() {
	*x = AdminListAllProductsRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListAllProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListAllProductsRequest) ProtoMessage() {}

func (x *AdminListAllProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListAllProductsRequest.ProtoReflect.Descriptor instead.
func (*AdminListAllProductsRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{6}
}

type AdminListAllProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*AdminProduct        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListAllProductsResponse) Reset() {
	*x = AdminListAllProductsResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListAllProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListAllProductsResponse) ProtoMessage() {}

func (x *AdminListAllProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListAllProductsResponse.ProtoReflect.Descriptor instead.
func (*AdminListAllProductsResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminListAllProductsResponse) GetProducts() []*AdminProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type AdminProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProduct) Reset() {
	*x = AdminProduct{}
	mi := &file_pb_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProduct) ProtoMessage() {}

func (x *AdminProduct) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProduct.ProtoReflect.Descriptor instead.
func (*AdminProduct) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProduct) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AdminProduct) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AdminGetProductByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProductByIdRequest) Reset() {
	*x = AdminGetProductByIdRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProductByIdRequest) ProtoMessage() {}

func (x *AdminGetProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProductByIdRequest.ProtoReflect.Descriptor instead.
func (*AdminGetProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGetProductByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminGetProductByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetProductByIdResponse) Reset() {
	*x = AdminGetProductByIdResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetProductByIdResponse) ProtoMessage() {}

func (x *AdminGetProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetProductByIdResponse.ProtoReflect.Descriptor instead.
func (*AdminGetProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminGetProductByIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminGetProductByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminGetProductByIdResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AdminGetProductByIdResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AdminListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersRequest) Reset() {
	*x = AdminListUsersRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersRequest) ProtoMessage() {}

func (x *AdminListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersRequest.ProtoReflect.Descriptor instead.
func (*AdminListUsersRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{11}
}

type AdminListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersResponse) Reset() {
	*x = AdminListUsersResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersResponse) ProtoMessage() {}

func (x *AdminListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersResponse.ProtoReflect.Descriptor instead.
func (*AdminListUsersResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminListUsersResponse) GetUsers() []*AdminUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,3,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_pb_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUser) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type AdminDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserRequest) Reset() {
	*x = AdminDeleteUserRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserRequest) ProtoMessage() {}

func (x *AdminDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminDeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserResponse) Reset() {
	*x = AdminDeleteUserResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserResponse) ProtoMessage() {}

func (x *AdminDeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserResponse.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminDeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminBlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBlockUserRequest) Reset() {
	*x = AdminBlockUserRequest{}
	mi := &file_pb_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBlockUserRequest) ProtoMessage() {}

func (x *AdminBlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBlockUserRequest.ProtoReflect.Descriptor instead.
func (*AdminBlockUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminBlockUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminBlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminBlockUserResponse) Reset() {
	*x = AdminBlockUserResponse{}
	mi := &file_pb_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBlockUserResponse) ProtoMessage() {}

func (x *AdminBlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBlockUserResponse.ProtoReflect.Descriptor instead.
func (*AdminBlockUserResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminBlockUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_proto_admin_proto protoreflect.FileDescriptor

const file_pb_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x14pb/proto/admin.proto\x12\x05admin\"^\n" +
	"\x16AdminAddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\")\n" +
	"\x17AdminAddProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"q\n" +
	"\x19AdminUpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"6\n" +
	"\x1aAdminUpdateProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x19AdminDeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x1aAdminDeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1d\n" +
	"\x1bAdminListAllProductsRequest\"O\n" +
	"\x1cAdminListAllProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.admin.AdminProductR\bproducts\"d\n" +
	"\fAdminProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\",\n" +
	"\x1aAdminGetProductByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"s\n" +
	"\x1bAdminGetProductByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"\x17\n" +
	"\x15AdminListUsersRequest\"@\n" +
	"\x16AdminListUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.admin.AdminUserR\x05users\"P\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x03 \x01(\bR\tisBlocked\"(\n" +
	"\x16AdminDeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x17AdminDeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15AdminBlockUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16AdminBlockUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9d\x05\n" +
	"\fAdminService\x12K\n" +
	"\n" +
	"AddProduct\x12\x1d.admin.AdminAddProductRequest\x1a\x1e.admin.AdminAddProductResponse\x12T\n" +
	"\rUpdateProduct\x12 .admin.AdminUpdateProductRequest\x1a!.admin.AdminUpdateProductResponse\x12T\n" +
	"\rDeleteProduct\x12 .admin.AdminDeleteProductRequest\x1a!.admin.AdminDeleteProductResponse\x12Z\n" +
	"\x0fListAllProducts\x12\".admin.AdminListAllProductsRequest\x1a#.admin.AdminListAllProductsResponse\x12W\n" +
	"\x0eGetProductById\x12!.admin.AdminGetProductByIdRequest\x1a\".admin.AdminGetProductByIdResponse\x12H\n" +
	"\tListUsers\x12\x1c.admin.AdminListUsersRequest\x1a\x1d.admin.AdminListUsersResponse\x12K\n" +
	"\n" +
	"DeleteUser\x12\x1d.admin.AdminDeleteUserRequest\x1a\x1e.admin.AdminDeleteUserResponse\x12H\n" +
	"\tBlockUser\x12\x1c.admin.AdminBlockUserRequest\x1a\x1d.admin.AdminBlockUserResponseB\fZ\n" +
	"/pb/admin/b\x06proto3"

var (
	file_pb_proto_admin_proto_rawDescOnce sync.Once
	file_pb_proto_admin_proto_rawDescData []byte
)

func file_pb_proto_admin_proto_rawDescGZIP() []byte {
	file_pb_proto_admin_proto_rawDescOnce.Do(func() {
		file_pb_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_proto_admin_proto_rawDesc), len(file_pb_proto_admin_proto_rawDesc)))
	})
	return file_pb_proto_admin_proto_rawDescData
}

var file_pb_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_proto_admin_proto_goTypes = []any{
	(*AdminAddProductRequest)(nil),       // 0: admin.AdminAddProductRequest
	(*AdminAddProductResponse)(nil),      // 1: admin.AdminAddProductResponse
	(*AdminUpdateProductRequest)(nil),    // 2: admin.AdminUpdateProductRequest
	(*AdminUpdateProductResponse)(nil),   // 3: admin.AdminUpdateProductResponse
	(*AdminDeleteProductRequest)(nil),    // 4: admin.AdminDeleteProductRequest
	(*AdminDeleteProductResponse)(nil),   // 5: admin.AdminDeleteProductResponse
	(*AdminListAllProductsRequest)(nil),  // 6: admin.AdminListAllProductsRequest
	(*AdminListAllProductsResponse)(nil), // 7: admin.AdminListAllProductsResponse
	(*AdminProduct)(nil),                 // 8: admin.AdminProduct
	(*AdminGetProductByIdRequest)(nil),   // 9: admin.AdminGetProductByIdRequest
	(*AdminGetProductByIdResponse)(nil),  // 10: admin.AdminGetProductByIdResponse
	(*AdminListUsersRequest)(nil),        // 11: admin.AdminListUsersRequest
	(*AdminListUsersResponse)(nil),       // 12: admin.AdminListUsersResponse
	(*AdminUser)(nil),                    // 13: admin.AdminUser
	(*AdminDeleteUserRequest)(nil),       // 14: admin.AdminDeleteUserRequest
	(*AdminDeleteUserResponse)(nil),      // 15: admin.AdminDeleteUserResponse
	(*AdminBlockUserRequest)(nil),        // 16: admin.AdminBlockUserRequest
	(*AdminBlockUserResponse)(nil),       // 17: admin.AdminBlockUserResponse
}
var file_pb_proto_admin_proto_depIdxs = []int32{
	8,  // 0: admin.AdminListAllProductsResponse.products:type_name -> admin.AdminProduct
	13, // 1: admin.AdminListUsersResponse.users:type_name -> admin.AdminUser
	0,  // 2: admin.AdminService.AddProduct:input_type -> admin.AdminAddProductRequest
	2,  // 3: admin.AdminService.UpdateProduct:input_type -> admin.AdminUpdateProductRequest
	4,  // 4: admin.AdminService.DeleteProduct:input_type -> admin.AdminDeleteProductRequest
	6,  // 5: admin.AdminService.ListAllProducts:input_type -> admin.AdminListAllProductsRequest
	9,  // 6: admin.AdminService.GetProductById:input_type -> admin.AdminGetProductByIdRequest
	11, // 7: admin.AdminService.ListUsers:input_type -> admin.AdminListUsersRequest
	14, // 8: admin.AdminService.DeleteUser:input_type -> admin.AdminDeleteUserRequest
	16, // 9: admin.AdminService.BlockUser:input_type -> admin.AdminBlockUserRequest
	1,  // 10: admin.AdminService.AddProduct:output_type -> admin.AdminAddProductResponse
	3,  // 11: admin.AdminService.UpdateProduct:output_type -> admin.AdminUpdateProductResponse
	5,  // 12: admin.AdminService.DeleteProduct:output_type -> admin.AdminDeleteProductResponse
	7,  // 13: admin.AdminService.ListAllProducts:output_type -> admin.AdminListAllProductsResponse
	10, // 14: admin.AdminService.GetProductById:output_type -> admin.AdminGetProductByIdResponse
	12, // 15: admin.AdminService.ListUsers:output_type -> admin.AdminListUsersResponse
	15, // 16: admin.AdminService.DeleteUser:output_type -> admin.AdminDeleteUserResponse
	17, // 17: admin.AdminService.BlockUser:output_type -> admin.AdminBlockUserResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pb_proto_admin_proto_init() }
func file_pb_proto_admin_proto_init() {
	if File_pb_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_proto_admin_proto_rawDesc), len(file_pb_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_admin_proto_goTypes,
		DependencyIndexes: file_pb_proto_admin_proto_depIdxs,
		MessageInfos:      file_pb_proto_admin_proto_msgTypes,
	}.Build()
	File_pb_proto_admin_proto = out.File
	file_pb_proto_admin_proto_goTypes = nil
	file_pb_proto_admin_proto_depIdxs = nil
}
